# Generated by Django 3.2.6 on 2021-09-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
