# Generated by Django 3.2.6 on 2021-09-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='text',
        ),
    ]
