# Generated by Django 3.2.6 on 2021-09-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_remove_event_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
