# Generated by Django 3.2.6 on 2021-09-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_event_flyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.ImageField(upload_to=''),
        ),
    ]
