# Generated by Django 3.2.6 on 2021-09-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210906_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
