# Generated by Django 3.2.6 on 2021-09-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_event_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='img',
        ),
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.URLField(default='https://drive.google.com/uc?id='),
        ),
    ]
