# Generated by Django 3.2.6 on 2021-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(),
        ),
    ]
