# Generated by Django 3.2.6 on 2021-09-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='flyer',
            field=models.URLField(),
        ),
    ]
