# Generated by Django 3.2.6 on 2021-09-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
