# Generated by Django 3.2.6 on 2021-10-27 15:52

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20210926_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='HustleChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_guest', models.CharField(blank=True, max_length=250)),
                ('episode', models.IntegerField()),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
