# Generated by Django 3.2.6 on 2021-11-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_nodalofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile_image', models.URLField()),
                ('linkedin_url', models.CharField(blank=True, max_length=250)),
                ('twitter_url', models.CharField(blank=True, max_length=250)),
                ('instagram_url', models.CharField(blank=True, max_length=250)),
                ('position', models.CharField(choices=[('Student Lead', 'Student Lead'), ('Technology Lead', 'Technology Lead'), ('Quality and Operations Lead', 'Quality and Operations Lead'), ('Community Lead', ' Community Lead'), ('Creative and Innovations Lead', 'Creative and Innovations Lead'), ('Finance Lead', 'Finance Lead'), ('Branding and Marketing Lead', 'Branding and Marketing Lead')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
